# Generated by Django 5.2 on 2025-04-09 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('DL', 'Delhi'), ('TN', 'Tamil Nadu'), ('GJ', 'Gujarat')], max_length=2)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('rate', models.IntegerField()),
                ('way', models.BooleanField()),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('map_location', models.CharField(max_length=255)),
            ],
        ),
    ]
