# Generated by Django 5.2 on 2025-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='map_location',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
