# Generated by Django 5.2 on 2025-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landify', '0002_remove_userresponse_map_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
