# Generated by Django 5.2 on 2025-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landify', '0003_contactsubmission_alter_userresponse_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='area',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
