# Generated by Django 5.2 on 2025-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landify', '0004_userresponse_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='area',
            field=models.CharField(blank=True, default='not_given', max_length=15),
        ),
    ]
